variables:
  - &slow_check_paths
    - path:
        - "**/*.kt"
        - "**/*.gradle"
        - ".woodpecker.yml"

pipeline:
  prettier_markdown_check:
    image: tmknom/prettier
    commands:
      - prettier -c "*.md" "*.yml"

  check_formatting:
    image: cimg/android:2023.06
    commands:
      - sudo chown -R circleci:circleci .
      - ./gradlew lintKotlin
    environment:
      GRADLE_RO_DEP_CACHE: .depcache
    when: *slow_check_paths

  build_project:
    image: cimg/android:2023.06
    commands:
      - sudo chown -R circleci:circleci .
      - ./gradlew assembleDebug
    environment:
      GRADLE_RO_DEP_CACHE: .depcache
    when: *slow_check_paths

  run_tests:
    image: cimg/android:2023.06
    commands:
      - sudo chown -R circleci:circleci .
      - ./gradlew testDebug
    environment:
      GRADLE_RO_DEP_CACHE: .depcache
    when: *slow_check_paths

  notify:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -d'Jerboa build ${CI_BUILD_STATUS}: ${CI_BUILD_LINK}' ntfy.sh/jerboa_ci"
    when:
      status: [failure, success]
